sudo: false
language: python
cache: pip
python:
- '3.8'
env:
- DJANGO="django~=2.2"
- DJANGO="django~=3.0"
- DJANGO="django~=3.1"
- DJANGO="django~=3.2"
- DJANGO="https://github.com/django/django/archive/main.tar.gz"
matrix:
  allow_failures:
  - env: DJANGO="https://github.com/django/django/archive/main.tar.gz"

before_install:
- pip install codecov
install:
- pip install $DJANGO django-storages djangorestframework boto3 -e .
script:
- coverage run --rcfile=.coveragerc runtests.py
after_success:
- codecov
branches:
  only:
  - master
